language: java

install: true

dist: xenial

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    
services:
  - xvfb
  - docker
    
addons:
  sonarcloud:
    organization: "caterinoa"

matrix:
  include:
    - jdk: openjdk8
      if: type IN (push) AND branch NOT IN (master, integration)
      script: ./mvnw clean verify -Pjacoco -Ppitest && ./mvnw coveralls:report
    - jdk: openjdk8
      if: type IN (push) AND branch IN (master, integration)
      script: ./mvnw clean verify -Pjacoco && ./mvnw coveralls:report
    - jdk: openjdk8
      if: type IN (pull_request)
      script: ./mvnw clean verify -Pjacoco && ./mvnw verify -Pe2e-tests && ./mvnw coveralls:report
    - jdk: openjdk11
      if: type IN (push) AND branch NOT IN (master, integration)
      script: ./mvnw clean verify -Pjacoco -Ppitest && ./mvnw coveralls:report sonar:sonar      
    - jdk: openjdk11
      if: type IN (push) AND branch IN (master, integration)
      script: ./mvnw clean verify -Pjacoco && ./mvnw coveralls:report sonar:sonar
    - jdk: openjdk11
      if: type IN (pull_request)
      script: ./mvnw clean verify -Pjacoco && ./mvnw verify -Pe2e-tests && ./mvnw coveralls:report sonar:sonar
      