language: java

install: true

dist: xenial

cache:
  directories:
    - $HOME/.m2
    
addons:
  sonarcloud:
    organization: "caterinoa"
    token:
      secure: "**************************"

matrix:
  include:
    - jdk: openjdk8
      script: ./mvn
    - jdk: openjdk11
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=caterinoa_project-planner