language: java

install: true

dist: xenial

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar.cache
    
addons:
  sonarcloud:
    organization: "caterinoa"
    token:
      secure: "**************************"

matrix:
  include:
    - jdk: openjdk8
      script: 
        - mvn clean verify -DskipCoverage=true -DskipMutation=true
    - jdk: openjdk11
      script: 
        - mvn clean verify -DskipCoverage=true -DskipMutation=true
        # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
        #- ./mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=caterinoa_project-planner