language: java

install: true

dist: xenial

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    
addons:
  sonarcloud:
    organization: "caterinoa"

matrix:
  include:
    - jdk: openjdk8
      if: type IN (push)
      script: ./mvnw clean verify -Pjacoco -Ppitest && ./mvnw coveralls:report
    - jdk: openjdk8
      if: type IN (pull_request) AND branch = master
      script: ./mvnw clean verify -Pjacoco -Ppitest && ./mvnw verify -Pe2e-tests && ./mvnw coveralls:report
    - jdk: openjdk11
      if: type IN (push)
      script: ./mvnw clean verify -Pjacoco -Ppitest && ./mvnw coveralls:report sonar:sonar
    - jdk: openjdk11
      if: type IN (pull_request) AND branch = master
      script: ./mvnw clean verify -Pjacoco -Ppitest && ./mvnw verify -Pe2e-tests && ./mvnw coveralls:report sonar:sonar
      